// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_lZcOUhXfldsVUo8Gp_32v_rteVV62G4',
    appId: '1:643233303879:web:242b9fe1f817877dc3d062',
    messagingSenderId: '643233303879',
    projectId: 'notif-tugas-6ff68',
    authDomain: 'notif-tugas-6ff68.firebaseapp.com',
    storageBucket: 'notif-tugas-6ff68.appspot.com',
    measurementId: 'G-K47J1ZFX0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrAraVVBs1cyLrgw83SzsIZvh29hkt6hA',
    appId: '1:643233303879:android:d8d01bc8ee37d504c3d062',
    messagingSenderId: '643233303879',
    projectId: 'notif-tugas-6ff68',
    storageBucket: 'notif-tugas-6ff68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUEDmf7f1yyHch_MsmsXv0dcD1DsZCkF0',
    appId: '1:643233303879:ios:9642dbb2b906e862c3d062',
    messagingSenderId: '643233303879',
    projectId: 'notif-tugas-6ff68',
    storageBucket: 'notif-tugas-6ff68.appspot.com',
    iosBundleId: 'com.example.xicRoster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUEDmf7f1yyHch_MsmsXv0dcD1DsZCkF0',
    appId: '1:643233303879:ios:79244d26ca7664e2c3d062',
    messagingSenderId: '643233303879',
    projectId: 'notif-tugas-6ff68',
    storageBucket: 'notif-tugas-6ff68.appspot.com',
    iosBundleId: 'com.example.xicRoster.RunnerTests',
  );
}
